name: Deploy Doxygen Documentation

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: ./Doxyfile
          working-directory: ./docs/doxygen/
      - name: Pages Deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/doxygen/html/
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: github-pages
